name: votenet
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- black
- cffi
- cmake
- cudatoolkit
- cython
- ipython
- jupyter
- jupyterlab
- loguru
- matplotlib
- meshio
- mkl
- nb_conda
- numpy
- opencv
- pandas
- pillow
- pip
- pytorch
- pytorch_geometric
- pyyaml
- scikit-image
- scikit-learn
- scipy
- seaborn
- setuptools
- transformers
- trimesh
- torchvision
- tqdm
- transformers
- wandb
